[build]
builder = "nixpacks"

[deploy]
startCommand = "python3 server.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
FLASK_ENV = "production"
PYTHONUNBUFFERED = "1"
